### ISSUE TITLE
react-hook-form

### ISSUE THREAD

**Issue by brunopaolo** [GeekyAnts/nativebase-docs#35]
**Describe the bug**
I'm using react-hook-form, the first example, but I got this error:

TypeError: undefined is not an object (evaluating 'errors.firstName')

**To Reproduce**
follow your guideline

**Screenshots**
<img width="1253" alt="Schermata 2021-08-03 alle 07 51 36" src="https://user-images.githubusercontent.com/14888145/127964828-a1268d49-df22-4b2c-b7d5-aea439ad721d.png">

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 11
 - OS: Android 11
 - expo 
 - Version 4.9.1

**Comment by ZeroGodForce** [comment]
I think the prop structure for `useForm()` has changed since this example was last updated or (at least it doesn't work on React Native properly).  Errors now exist inside a `formState` object.  Try changing the line:

```javascript
  const { control, handleSubmit, errors } = useForm();
```
To this:
```javascript
  const { control, handleSubmit, formState: { errors } } = useForm();
```

**Source:** https://react-hook-form.com/get-started#ReactNative.  

As a side note, the render prop on the `<Controller>` also looks like it's changed from:

```javascript
<Controller
    control={control}
    render={({ onChange, onBlur, value }) => (
        <Input
```

to:

```javascript
<Controller
    control={control}
    render={({ field: { onChange, onBlur, value } }) => (
        <Input
```

This is what worked for me.  Best to cross-reference the native base example with the example on the React Hook Form website for now until the examples are updated.  Hope this helps.

**Comment by brunopaolo** [comment]
> I think the prop structure for `useForm()` has changed since this example was last updated or (at least it doesn't work on React Native properly). Errors now exist inside a `formState` object. Try changing the line:
> 
> ```js
>   const { control, handleSubmit, errors } = useForm();
> ```
> 
> To this:
> 
> ```js
>   const { control, handleSubmit, formState: { errors } } = useForm();
> ```
> 
> **Source:** https://react-hook-form.com/get-started#ReactNative.
> 
> As a side note, the render prop on the `<Controller>` also looks like it's changed from:
> 
> ```js
> <Controller
>     control={control}
>     render={({ onChange, onBlur, value }) => (
>         <Input
> ```
> 
> to:
> 
> ```js
> <Controller
>     control={control}
>     render={({ field: { onChange, onBlur, value } }) => (
>         <Input
> ```
> 
> This is what worked for me. Best to cross-reference the native base example with the example on the React Hook Form website for now until the examples are updated. Hope this helps.

Thanks now It's work.
